// SPDX-FileCopyrightText: 2026 Georges Martin <jrjsmrtn@gmail.com>
// SPDX-License-Identifier: Apache-2.0

package lockfile

import (
	"fmt"
	"strings"
)

// requirements mirrors the shape ansible-galaxy accepts for `install -r`.
type requirements struct {
	Collections []requirement `yaml:"collections,omitempty"`
	Roles       []requirement `yaml:"roles,omitempty"`
}

type requirement struct {
	Name    string `yaml:"name"`
	Version string `yaml:"version,omitempty"`
	// Src, SCM, Type and Source appear only on an entry carried through from a declaration.
	// They are emitted verbatim as the operator wrote them: this tool did not derive them, and
	// re-deriving a source it never observed is exactly what it refuses to do elsewhere.
	Src    string `yaml:"src,omitempty"`
	SCM    string `yaml:"scm,omitempty"`
	Type   string `yaml:"type,omitempty"`
	Source string `yaml:"source,omitempty"`
}

// Declared is one entry recovered from a requirements.yml, keyed by the name the content installs
// under. Only declarations this tool can match by name reach here — see CarryThrough.
type Declared struct {
	Name    string
	Version string
	Src     string
	SCM     string
	Type    string
	Source  string
}

// Immutable reports whether the declared ref pins something that cannot move.
//
// Only a full 40-character hex SHA qualifies. A branch is obviously mutable; a TAG is not
// obviously immutable — it can be moved or deleted upstream — so this refuses to call one a pin.
// Erring the other way would let the projection promise reproducibility it cannot deliver, which
// is the promise the whole tool exists to keep honest.
func (d Declared) Immutable() bool {
	v := strings.TrimSpace(d.Version)
	if len(v) != 40 {
		return false
	}
	for _, r := range v {
		if !(r >= '0' && r <= '9' || r >= 'a' && r <= 'f' || r >= 'A' && r <= 'F') {
			return false
		}
	}
	return true
}

// galaxyOrigin is the one origin this projection can express. It mirrors content.OriginGalaxy;
// the lockfile stores origins as strings, and comparing against the string keeps this package
// from depending on the content package's type for a single comparison.
const galaxyOrigin = "galaxy"

const requirementsHeader = `# Generated by 'ansible-bom lock --requirements' — every component
# pinned to the version currently installed. Install with:
#
#     ansible-galaxy install -r <this file>
#
# Caveats worth knowing before you rely on it:
#   - ansible-galaxy cannot verify artefact hashes on install. Pinning a
#     version does not prevent that version being republished with different
#     content; 'ansible-bom verify' against the resulting tree detects that.
#   - components listed as 'unpinnable' in the lockfile are ABSENT here,
#     because they have no version to install. A tree rebuilt from this file
#     will be missing them.
#   - so are components whose recorded origin is not 'galaxy', UNLESS their
#     source was recovered from a requirements.yml passed with -r.
#     ansible-galaxy resolves a bare name/version pair from a Galaxy server
#     and nowhere else, so emitting one it cannot resolve fails the WHOLE
#     run — every other collection included. Anything omitted is listed below.
`

// Omitted records what the projection left out, and why. Nothing is dropped silently: every
// entry here is named in the file's header and on stderr.
type Omitted struct {
	// Unpinnable have no version at all, so there is nothing to install.
	Unpinnable []Unpinnable
	// OffGalaxy are pinned and installed, but their origin is not recorded as galaxy, and no
	// declaration was supplied that names them.
	OffGalaxy []Entry
	// NotImmutable were carried through from a declaration whose ref can still move. They ARE
	// in the file; they are listed because a reinstall from them is not guaranteed to reproduce
	// this tree, and a projection that stayed quiet would overstate what it promises.
	NotImmutable []Entry
}

// Len is the total number of components the projection cannot carry.
func (o Omitted) Len() int { return len(o.Unpinnable) + len(o.OffGalaxy) }

// Requirements projects a lockfile into a requirements.yml that ansible-galaxy can install from.
//
// This is the reproducibility payoff: the lockfile records what is installed, and this projection
// reinstalls it. It is deliberately lossy — origin, tier, digests and declared constraints are
// dropped, because ansible-galaxy has nowhere to put them.
//
// Only components whose origin is 'galaxy' are emitted. `install -r` resolves a bare name/version
// pair against a Galaxy server, so a component sourced from git or a local path has no
// representation in this format at all. Emitting one anyway does not merely fail for that
// component: ansible-galaxy resolves the whole file as one dependency problem, so a single
// unresolvable requirement aborts the run and NOTHING is installed.
//
// Note the asymmetry this creates, and the direction it errs in. Origin 'unknown' means the tree
// carries no install marker, not that the component is definitely off-Galaxy — so a Galaxy
// collection whose marker is missing is omitted here. That produces an incomplete file, which the
// header and stderr both announce; the alternative produces a file that installs nothing and
// blames the wrong component.
func Requirements(l Lock, declared map[string]Declared) ([]byte, Omitted, error) {
	var r requirements
	om := Omitted{Unpinnable: l.Unpinnable}

	project := func(e Entry) (requirement, bool) {
		if e.Origin == galaxyOrigin {
			return requirement{Name: e.Name, Version: e.Version}, true
		}
		d, ok := declared[e.Name]
		if !ok {
			return requirement{}, false
		}
		// Verbatim. The operator wrote this and it installs; re-deriving a source this tool
		// never observed is what the omission rule exists to prevent.
		return requirement{
			Name: d.Name, Version: d.Version, Src: d.Src,
			SCM: d.SCM, Type: d.Type, Source: d.Source,
		}, true
	}

	carry := func(e Entry, into *[]requirement) {
		req, ok := project(e)
		if !ok {
			om.OffGalaxy = append(om.OffGalaxy, e)
			return
		}
		*into = append(*into, req)
		if d, carried := declared[e.Name]; carried && e.Origin != galaxyOrigin && !d.Immutable() {
			om.NotImmutable = append(om.NotImmutable, e)
		}
	}

	for _, e := range l.Collections {
		carry(e, &r.Collections)
	}
	for _, e := range l.Roles {
		carry(e, &r.Roles)
	}

	enc, err := encodeYAML(r)
	if err != nil {
		return nil, Omitted{}, fmt.Errorf("encoding requirements: %w", err)
	}

	var sb strings.Builder
	sb.WriteString(requirementsHeader)
	if len(om.Unpinnable) > 0 {
		fmt.Fprintf(&sb, "#\n# OMITTED: %d component(s) on the source node have no version and cannot be installed\n",
			len(om.Unpinnable))
		for _, u := range om.Unpinnable {
			fmt.Fprintf(&sb, "#   - %s (%s)\n", u.Name, u.Kind)
		}
	}
	if len(om.NotImmutable) > 0 {
		fmt.Fprintf(&sb, "#\n# CARRIED THROUGH from your requirements.yml, but NOT immutably pinned.\n"+
			"# These reinstall whatever the ref points at on the day, not what is installed\n"+
			"# now. Only a full commit SHA counts as immutable here; a tag can be moved.\n")
		for _, e := range om.NotImmutable {
			fmt.Fprintf(&sb, "#   - %s\n", e.Name)
		}
	}
	if len(om.OffGalaxy) > 0 {
		fmt.Fprintf(&sb, "#\n# OMITTED: %d component(s) are pinned but not installable from Galaxy by name.\n"+
			"# Reinstall them from their original source; this file cannot express it.\n",
			len(om.OffGalaxy))
		for _, e := range om.OffGalaxy {
			fmt.Fprintf(&sb, "#   - %s %s (origin: %s)\n", e.Name, e.Version, e.Origin)
		}
	}
	sb.WriteString("\n")
	sb.WriteString(documentStart)
	sb.Write(enc)

	return []byte(sb.String()), om, nil
}
