package lockfile

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// requirements mirrors the shape ansible-galaxy accepts for `install -r`.
type requirements struct {
	Collections []requirement `yaml:"collections,omitempty"`
	Roles       []requirement `yaml:"roles,omitempty"`
}

type requirement struct {
	Name    string `yaml:"name"`
	Version string `yaml:"version"`
}

const requirementsHeader = `# Generated by 'ansible-bom lock --requirements' — every component pinned to the version
# currently installed. Install with:
#
#     ansible-galaxy install -r <this file>
#
# Caveats worth knowing before you rely on it:
#   - ansible-galaxy cannot verify artefact hashes on install. Pinning a version does not
#     prevent that version being republished with different content; 'ansible-bom verify'
#     against the resulting tree is what detects that.
#   - components listed as 'unpinnable' in the lockfile are ABSENT here, because they have no
#     version to install. A tree rebuilt from this file will be missing them.
`

// Requirements projects a lockfile into a requirements.yml that ansible-galaxy can install from.
//
// This is the reproducibility payoff: the lockfile records what is installed, and this projection
// reinstalls it. It is deliberately lossy — origin, tier, digests and declared constraints are
// dropped, because ansible-galaxy has nowhere to put them.
//
// Unpinnable components are omitted and reported in the returned count, never silently dropped.
func Requirements(l Lock) ([]byte, int, error) {
	var r requirements
	for _, e := range l.Collections {
		r.Collections = append(r.Collections, requirement{Name: e.Name, Version: e.Version})
	}
	for _, e := range l.Roles {
		r.Roles = append(r.Roles, requirement{Name: e.Name, Version: e.Version})
	}

	enc, err := yaml.Marshal(r)
	if err != nil {
		return nil, 0, fmt.Errorf("encoding requirements: %w", err)
	}

	var sb strings.Builder
	sb.WriteString(requirementsHeader)
	if len(l.Unpinnable) > 0 {
		fmt.Fprintf(&sb, "#\n# OMITTED: %d component(s) on the source node have no version and cannot be installed\n",
			len(l.Unpinnable))
		for _, u := range l.Unpinnable {
			fmt.Fprintf(&sb, "#   - %s (%s)\n", u.Name, u.Kind)
		}
	}
	sb.WriteString("\n")
	sb.Write(enc)

	return []byte(sb.String()), len(l.Unpinnable), nil
}
