// SPDX-FileCopyrightText: 2026 Georges Martin <jrjsmrtn@gmail.com>
// SPDX-License-Identifier: Apache-2.0

package lockfile

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// requirements mirrors the shape ansible-galaxy accepts for `install -r`.
type requirements struct {
	Collections []requirement `yaml:"collections,omitempty"`
	Roles       []requirement `yaml:"roles,omitempty"`
}

type requirement struct {
	Name    string `yaml:"name"`
	Version string `yaml:"version"`
}

// galaxyOrigin is the one origin this projection can express. It mirrors content.OriginGalaxy;
// the lockfile stores origins as strings, and comparing against the string keeps this package
// from depending on the content package's type for a single comparison.
const galaxyOrigin = "galaxy"

const requirementsHeader = `# Generated by 'ansible-bom lock --requirements' — every component pinned to the version
# currently installed. Install with:
#
#     ansible-galaxy install -r <this file>
#
# Caveats worth knowing before you rely on it:
#   - ansible-galaxy cannot verify artefact hashes on install. Pinning a version does not
#     prevent that version being republished with different content; 'ansible-bom verify'
#     against the resulting tree is what detects that.
#   - components listed as 'unpinnable' in the lockfile are ABSENT here, because they have no
#     version to install. A tree rebuilt from this file will be missing them.
#   - so are components whose recorded origin is not 'galaxy'. ansible-galaxy resolves a bare
#     name/version pair from a Galaxy server and nowhere else, so emitting one it cannot
#     resolve fails the WHOLE run — every other collection included. They are listed below.
`

// Omitted records what the projection left out, and why. Nothing is dropped silently: every
// entry here is named in the file's header and on stderr.
type Omitted struct {
	// Unpinnable have no version at all, so there is nothing to install.
	Unpinnable []Unpinnable
	// OffGalaxy are pinned and installed, but their origin is not recorded as galaxy.
	OffGalaxy []Entry
}

// Len is the total number of components the projection cannot carry.
func (o Omitted) Len() int { return len(o.Unpinnable) + len(o.OffGalaxy) }

// Requirements projects a lockfile into a requirements.yml that ansible-galaxy can install from.
//
// This is the reproducibility payoff: the lockfile records what is installed, and this projection
// reinstalls it. It is deliberately lossy — origin, tier, digests and declared constraints are
// dropped, because ansible-galaxy has nowhere to put them.
//
// Only components whose origin is 'galaxy' are emitted. `install -r` resolves a bare name/version
// pair against a Galaxy server, so a component sourced from git or a local path has no
// representation in this format at all. Emitting one anyway does not merely fail for that
// component: ansible-galaxy resolves the whole file as one dependency problem, so a single
// unresolvable requirement aborts the run and NOTHING is installed.
//
// Note the asymmetry this creates, and the direction it errs in. Origin 'unknown' means the tree
// carries no install marker, not that the component is definitely off-Galaxy — so a Galaxy
// collection whose marker is missing is omitted here. That produces an incomplete file, which the
// header and stderr both announce; the alternative produces a file that installs nothing and
// blames the wrong component.
func Requirements(l Lock) ([]byte, Omitted, error) {
	var r requirements
	om := Omitted{Unpinnable: l.Unpinnable}

	for _, e := range l.Collections {
		if e.Origin != galaxyOrigin {
			om.OffGalaxy = append(om.OffGalaxy, e)
			continue
		}
		r.Collections = append(r.Collections, requirement{Name: e.Name, Version: e.Version})
	}
	for _, e := range l.Roles {
		if e.Origin != galaxyOrigin {
			om.OffGalaxy = append(om.OffGalaxy, e)
			continue
		}
		r.Roles = append(r.Roles, requirement{Name: e.Name, Version: e.Version})
	}

	enc, err := yaml.Marshal(r)
	if err != nil {
		return nil, Omitted{}, fmt.Errorf("encoding requirements: %w", err)
	}

	var sb strings.Builder
	sb.WriteString(requirementsHeader)
	if len(om.Unpinnable) > 0 {
		fmt.Fprintf(&sb, "#\n# OMITTED: %d component(s) on the source node have no version and cannot be installed\n",
			len(om.Unpinnable))
		for _, u := range om.Unpinnable {
			fmt.Fprintf(&sb, "#   - %s (%s)\n", u.Name, u.Kind)
		}
	}
	if len(om.OffGalaxy) > 0 {
		fmt.Fprintf(&sb, "#\n# OMITTED: %d component(s) are pinned but not installable from Galaxy by name.\n"+
			"# Reinstall them from their original source; this file cannot express it.\n",
			len(om.OffGalaxy))
		for _, e := range om.OffGalaxy {
			fmt.Fprintf(&sb, "#   - %s %s (origin: %s)\n", e.Name, e.Version, e.Origin)
		}
	}
	sb.WriteString("\n")
	sb.Write(enc)

	return []byte(sb.String()), om, nil
}
